;[module/date]
type = internal/date
interval = 1.0

; See "man date" for details on how to format the date string
date = %a %d %b

; Optional time format
time = %H:%M

; If `date-alt` or `time-alt` is defined, clicking the module will toggle between formats
date-alt = %A, %d %B %Y
time-alt = %H:%M:%S

; Available tags:
;   <label> (default)
format =   <label>
;format-background = #88000000
format-padding = 3

; Available tokens:
;   %date%
;   %time%
; Default: %date%
label = %date% %time%
;label-font = 3
;label-foreground = #fff
