;[module/eth]
type = internal/network
interface = enp2s0
interval = 3.0
format-connected-underline = ${xrdb:color2}
format-connected-underline = ${xrdb:color10}
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%
format-disconnected =
format-disconnected = <label-disconnected>
format-disconnected-underline = ${self.format-connected-underline}
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.foreground-alt}
