[module/filesystem]
; info about mounted file systems
type = internal/fs

; Mountpoints to display
; Should be defined in config file that includes this module
;mount-0 = /
;mount-1 = /home/n/D

; Seconds to sleep between updates
; Default: 30
interval = 30

; Display fixed precision values
; Default: false
fixed-values = true

; Spacing between entries
; Default: 2
; set to 0 since margin-right is used in the labels below
spacing = 0

; Available tags:
;   <label-mounted> (default)
;   <bar-free>
;   <bar-used>
;   <ramp-capacity>
format-mounted = <label-mounted>

; Available tags:
;   <label-unmounted> (default)
format-unmounted = <label-unmounted>

; Available tokens:
;   %mountpoint%
;   %type%
;   %fsname%
;   %percentage_free%
;   %percentage_used%
;   %total%
;   %free%
;   %used%
; Default: %mountpoint% %percentage_free%%
label-mounted =  %mountpoint%: %free%
label-mounted-margin-right = 3

; Available tokens:
;   %mountpoint%
; Default: %mountpoint% is not mounted
label-unmounted =  %mountpoint%: not mounted
label-unmounted-foreground = #55
label-unmounted-margin-right = 3

;label-mounted = %{F#0a81f5}~%{F-}: %percentage_used%%
;label-unmounted = %mountpoint% not mounted
;label-unmounted-foreground = ${colors.foreground-alt}
