;[module/wifimenu]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
;expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with the additional
; "exec" property
;
; Available exec commands:
;   menu-open-LEVEL
;   menu-close
; Other commands will be executed using "/usr/bin/env sh -c $COMMAND"

menu-0-0 = Browsers
menu-0-0-exec = menu-open-1
menu-0-2 = Multimedia
menu-0-2-exec = menu-open-2

menu-1-0 = Firefox
menu-1-0-exec = firefox &
menu-1-1 = Chromium
menu-1-1-exec = chromium &

menu-2-0 = Gimp
menu-2-0-exec = gimp &
menu-2-1 = Scrot
menu-2-1-exec = scrot &

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
;format = <label-toggle> <menu>

label-open = Apps
label-close = x

; Optional item separator
; Default: none
label-separator = |
